# The workflow contains build and testing data structures implementations.

name: Workflow of data structures

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcc:latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        make dynamic_queue.o 
        make static_queue.o
